#ifndef KEYPRESS_H
#define KEYPRESS_H

#include <termios.h>
#include <unistd.h>

#define ENTER_KEYPRESS 10
#define LEFT_KEYPRESS 68
#define RIGHT_KEYPRESS 67
#define UP_KEYPRESS 66
#define DOWN_KEYPRESS 65
#define ZOOMIN_KEYPRESS 61
#define ZOOMOUT_KEYPRESS 45
#define A_KEYPRESS 97
#define B_KEYPRESS 98
#define C_KEYPRESS 99
#define D_KEYPRESS 100
#define E_KEYPRESS 101
#define F_KEYPRESS 102
#define G_KEYPRESS 103
#define H_KEYPRESS 104
#define I_KEYPRESS 105
#define J_KEYPRESS 106
#define K_KEYPRESS 107
#define L_KEYPRESS 108
#define M_KEYPRESS 109
#define N_KEYPRESS 110
#define O_KEYPRESS 111
#define P_KEYPRESS 112
#define Q_KEYPRESS 113
#define R_KEYPRESS 114
#define S_KEYPRESS 115
#define T_KEYPRESS 116
#define U_KEYPRESS 117
#define V_KEYPRESS 118
#define W_KEYPRESS 119
#define X_KEYPRESS 120
#define Y_KEYPRESS 121
#define Z_KEYPRESS 122
#define SPACE_KEYPRESS 32
#define LESSTHAN_KEYPRESS 44
#define MORETHAN_KEYPRESS 46
#define ZERO_KEYPRESS 48
#define ONE_KEYPRESS 49
#define TWO_KEYPRESS 50
#define THREE_KEYPRESS 51
#define FOUR_KEYPRESS 52
#define FIVE_KEYPRESS 53
#define SIX_KEYPRESS 54
#define SEVEN_KEYPRESS 55
#define EIGHT_KEYPRESS 56
#define NINE_KEYPRESS 57
int getch(void);


#endif